import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import PromotionalHeaderNav from "./Components/headerNavbar/PromotionalHeaderNav";
import TopNavbar from "./Components/headerNavbar/TopNavbar";
import Navbar from "./Components/headerNavbar/Navbar";
import Foter from "./Components/footerr/Footeer";
import "./globals.css";
const poppins = Poppins({
  weight: ["100", "300", "300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${poppins.className}  antialiased`}>
        <div>
          <PromotionalHeaderNav />
        </div>
        <div className="xl:block lg:block md:block sm:block">
          <TopNavbar />
          <Navbar />
        </div>
        <div className="mb-50">{children}</div>
        <br />
        <Foter />
      </body>
    </html>
  );
}
